### ISSUE TITLE
Partial fixes for recent update (Nova theme)

### ISSUE THREAD

**Issue by StarWolf3000** [tehbasshunter/theme-fixes#3]
The devs at Discord changed again some IDs and classes, this is a partial fix for the Nova theme, add them to the existing stylesheet or change the classes and IDs:
```css
/* Background */
.appMount-14L89u {
    background-image: url(https://i.imgur.com/h0YyOD7.png);
    background-size: cover;
}
.appMount-XYZfmp, .container-2OU7Cz, .channels-3g2vYe, .title-qAcLxz, .chat form, .headerBar-cxbhPD {
    background: transparent !important; 
}
.headerBar-cxbhPD {
	border-bottom-color: rgba(0,0,0,0.25) !important;
}
```

The whole file is here: https://pastebin.com/mMvD2W7z
